sudo: required
notifications:
  email:
    recipients:
      - karima.rafes@gmail.com
    on_success: always # default: change (other : never)
    on_failure: always # default: always

env:
  global:
    - URI="https://travis-ci.org/BorderCloud/tft_virtuoso7_stable/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Virtuoso Open-Source Edition"
    - VERSION="stable/7"
    - SPARQLSCORE_DATABASE="134.158.74.247"

language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - docker pull bordercloud/tft-jena-fuseki
  - docker pull bordercloud/tft-virtuoso7-stable
#  - docker build -t tft_virtuoso7_stable .

script:
# Deploy TFT
# Run RDF database in order to save tests and results
  -   docker run --privileged --name instance.tft_virtuoso7_stable -h tft_virtuoso7_stable -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft_database -d bordercloud/tft-jena-fuseki

#  -   docker run --privileged --name instance.tft_virtuoso7_stable -h tft_virtuoso7_stable -d tft_virtuoso7_stable
#  -   docker run --privileged --name instance.tft.example.org -h example.org -d tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d tft-virtuoso7-stable

  -   docker run --privileged --name instance.tft_database -d bordercloud/tft-jena-fuseki

  -   git clone --recursive https://github.com/BorderCloud/TFT.git
  -   cd TFT
  -   composer install --dev
#  -   ls
  -   php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
  -   php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt virtuoso -tq http://172.17.0.2:8890/sparql/ -tu http://172.17.0.2:8890/sparql/ -r ${URI} -o ./junit --softwareName="${NAME}" --softwareDescribeTag=${VERSION}
  -   php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}


#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
#    docker push bordercloud/tft_virtuoso7_stable;
#    fi

