sudo: required

language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - docker build -t tft_virtuoso7_stable .

script:
#  -   git clone --recursive https://github.com/BorderCloud/TFT.git
  -   ls
#  -   php ./TFT/tft-testsuite -a -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -d
#  -   php ./TFT/tft -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -tt fuseki -tq http://172.17.0.7/test/query -tu http://172.17.0.7/test/update -r https://github.com/BorderCloud/TFT/jena-fuseki/v3.4.0 -o ./junit --softwareName="Jena Fuseki"  --softwareDescribeTag=v3.4.0 -d
#  -   php ./TFT/tft-score -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -r  https://github.com/BorderCloud/TFT/jena-fuseki/v3.4.0  -d

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bordercloud/tft-virtuoso7-stable;
    fi
