sudo: required

language: php
php:
  -  7.4.15

notifications:
  email:
    recipients:
      - karima.rafes@gmail.com
    on_success: always # default: change (other : never)
    on_failure: always # default: always

env:
  global:
    - URI="https://travis-ci.org/BorderCloud/tft-virtuoso7-stable/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Virtuoso Open-Source Edition"
    - SOFTWARE_DESCRIBE="Virtuoso is a high-performance and scalable Multi-Model RDBMS, Data Integration Middleware, Linked Data Deployment, and HTTP Application Server Platform"
    - VERSION="stable/7"
    - SPARQLSCORE_DATABASE="134.158.74.239"
#    - SPARQLSCORE_DATABASE="172.18.0.6:8080" #local

services:
  - docker

before_install:
# Compile the docker's project 
  - docker build -t tft-virtuoso7-stable .
  - sudo docker-compose up -d 

script:
  - sleep 30s
  - git clone --recursive https://github.com/BorderCloud/TFT.git
  - cd TFT
# install SPARQL client 
  - composer install
# install JMeter 
  - wget http://mirrors.standaloneinstaller.com/apache//jmeter/binaries/apache-jmeter-5.4.1.tgz
  - tar xvzf apache-jmeter-5.4.1.tgz
  - mv  apache-jmeter-5.4.1 jmeter
  - rm apache-jmeter-5.4.1.tgz
  
  -   php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
  -   php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt virtuoso -te http://172.18.0.2/sparql -r ${URI} -o ./junit --softwareName="${NAME}" --softwareDescribeTag=${VERSION}  --softwareDescribe="${TRAVIS_COMMIT}"
  -   php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}

  -   docker-compose stop
 
# Save the Docker image
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker tag tft-virtuoso7-stable bordercloud/tft-virtuoso7-stable:latest ;
    docker push bordercloud/tft-virtuoso7-stable;
    fi
