name: Build

# At the end of this build, you can find the last version number of Virtuoso 7 stable

#on: push
on: workflow_dispatch
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image docker
        run: >-
            docker build -t tft-virtuoso7-stable .

