name: Publish

# REFRESH THE VERSION NUMBER BEFORE TO START THIS WORKFLOW

# Only trigger, when the test workflow succeeded
#on:
  #workflow_run:
    #workflows: ["Test"]
    #types:
      #- completed
      
on: workflow_dispatch

env:
    VERSION: "7.20.3233" 
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bordercloud/tft-virtuoso7-stable
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: bordercloud/tft-virtuoso7-stable:latest
      -
        name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
        with:
          destination_container_repo: bordercloud/tft-virtuoso7-stable
          provider: dockerhub
          short_description: 'bordercloud/tft-virtuoso7-stable'
          readme_file: 'README.md'
